### Signup a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "asdf@gmail.com",
  "password": "ngopi"
}

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "email": "konstanta@email.com"
}

### Delete a user
DELETE http://localhost:3000/auth/3

### Find a particular user with email
GET http://localhost:3000/auth?email=asdf@gmail.com
